save_dir: ./sampling_output/sdxl-cfg4/
# save_dir: ./sampling_output/3bw72n5ynm-epoch=4-step=9378


sampling_func:

  _target_: duwu.sampling.diffusion_sampling
  _partial_: true

  internal_sampling_func:
    _target_: duwu.sampling.sample_euler_ancestral
    # _target_: duwu.sampling.sample_dpm2
    _partial_: true
    eta: 0.0
    # single_call: false

  prompt:
    - "a cat sitting on a table"
    - "a photograph of an astronaut riding a horse"
    - "dogs with pumpkins"
    - "A priest holds a chalice aloft while another figure kneeling figure kneels on the floor, set against a backdrop of architectural details and ornamentation within what appears to be a religious setting."
  neg_prompt:
    - ""
    - ""
    - ""
    - ""
  num_samples: 8
  padding_mode: cycling
  cfg_scale: 4
  seed: 1215
  # num_steps: 4
  num_steps: 24
  width: 1024
  height: 1024
  # rescale: true
  # width: 256
  # height: 256

  train_scheduler:
    _target_: diffusers.EulerDiscreteScheduler.from_pretrained
    pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
    subfolder: scheduler
    # pretrained_model_name_or_path: KBlueLeaf/Laplace-scheduler
    # subfolder: laplace-1_0-cut-head

  # get_sigma_func:
  #   _target_: duwu.sampling.get_sigmas.get_sigmas_for_rf
  #   _partial_: true
  #   max_sigma: 14.6146
  #   time_disc_func:
  #     _target_: duwu.sampling.get_sigmas.sigmoid_time_scale
  #     _partial_: true
  #     rho: 10

  # sample_scheduler:
  #   _target_: diffusers.EulerDiscreteScheduler.from_pretrained
  #   pretrained_model_name_or_path: KBlueLeaf/Laplace-scheduler
  #   subfolder: laplace-1_0-cut-head
  #   # pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
  #   # subfolder: scheduler

  # vae_std: 13.3
  # vae_mean: 1.125


model_config:

  unet:
    _target_: diffusers.UNet2DConditionModel.from_pretrained
    _load_config_:
      device: cuda
      precision: torch.float16
      to_freeze: true
      # ckpt_path: checkpoints/qdzv3riudt-epoch=0-step=2000.ckpt
      # ckpt_path: checkpoints/3bw72n5ynm-epoch=4-step=9378.ckpt
      # ckpt_path: checkpoints/6wiuzzen5q-epoch=1-step=15000.ckpt
      # state_dict_key: state_dict
      # state_dict_prefix: unet.
    pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
    subfolder: unet

  te:
    _target_: duwu.modules.text_encoders.ConcatTextEncoders
    _load_config_:
      device: cuda
      precision: torch.float16
      to_freeze: true
    tokenizers:
    - openai/clip-vit-large-patch14
    - laion/CLIP-ViT-bigG-14-laion2B-39B-b160k
    text_model_and_configs:
    - 
      - _target_: transformers.CLIPTextModel.from_pretrained
        pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
        subfolder: text_encoder
      - disable_autocast: false
        concat_bucket: 0
        use_pooled: false
        need_mask: false
        layer_idx: -2
    - 
      - _target_: transformers.CLIPTextModel.from_pretrained
        pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
        subfolder: text_encoder_2
      - disable_autocast: false
        concat_bucket: 0
        use_pooled: true
        need_mask: false
        layer_idx: -2
    zero_for_padding: false

  vae:
    _target_: diffusers.AutoencoderKL.from_pretrained
    _load_config_:
      device: cuda
      precision: torch.float16
      to_freeze: true
    pretrained_model_name_or_path: madebyollin/sdxl-vae-fp16-fix
