seed: 1215

lightning_config:
  log_every_n_steps: 10
  max_steps: 1000
  precision: bf16-mixed
  fast_dev_run: true

data:
  
  _target_: duwu.data.TrainDataModule
  _recursive_: false

  dataset_config:
    _target_: duwu.data.DummyDataset
    sample_size: [4, 32, 32]
    n_samples: 50

  dataloader_config:
    batch_size: 16
    num_workers: 20

trainer:

  _target_: duwu.trainer.DMTrainer

  # Keep model_config as dictionary
  _recursive_: false

  lr: 1.0e-06
  # optimizer: lion_pytorch.Lion
  optimizer: torch.optim.AdamW
  opt_config:
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.999
  use_warm_up: false
  warm_up_period: 100

  model_config:
  
    unet:
      _target_: duwu.modules.unet_patch.UNet2DFromScratch.from_config
      config: stabilityai/stable-diffusion-xl-base-1.0
      subfolder: unet
  
    te:
      _target_: duwu.modules.text_encoders.ConcatTextEncoders
      _load_config_:
        precision: torch.float16
        to_freeze: true
      tokenizers:
      - openai/clip-vit-large-patch14
      - laion/CLIP-ViT-bigG-14-laion2B-39B-b160k
      text_model_and_configs:
      - 
        - _target_: transformers.CLIPTextModel.from_pretrained
          pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
          subfolder: text_encoder
        - disable_autocast: false
          concat_bucket: 0
          use_pooled: false
          need_mask: false
          layer_idx: -2
      - 
        - _target_: transformers.CLIPTextModel.from_pretrained
          pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
          subfolder: text_encoder_2
        - disable_autocast: false
          concat_bucket: 0
          use_pooled: true
          need_mask: false
          layer_idx: -2
      zero_for_padding: false
  
    vae: null
  
    scheduler:
      _target_: diffusers.EulerDiscreteScheduler.from_pretrained
      pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
      subfolder: scheduler
